hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/hypr/scripts/startup_script.sh")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("avizo-service")
    hl.exec_cmd("easyeffects --gapplication-service")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("quickshell -p ~/.config/hypr/qs-hyprview/shell.qml")
end)
