# Hellwal Colors for Mako

background-color=#%%color1.hex%%
text-color=#%%color15%%
border-color=#%%background%%

# Per-mode settings

[mode=do-not-disturb]
invisible=1
on-notify=none

[mode=silent]
on-notify=none

[urgency=high]
# Using color1 (Red/Error) for high urgency
border-color=#%%color1.hex%%
background-color=#%%background%%
text-color=#%%color1.hex%%