[meta]
version = 1
name = "Hellwal-Generated-Theme"
description = "Dynamically generated colors from wallpaper"
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
background = "%%background%%"
foreground = "%%color6%%"

[colors.list.item.selection]
background = "%%color6%%"
foreground = "%%color7%%"
