[meta]
version = 1
name = "Hellwal-Generated-Theme"
description = "Dynamically generated colors from wallpaper"
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
background = "%%color1%%"
foreground = "%%color7%%"
secondary_background = "%%color1%%"

[colors.list.item.selection]
background = "%%color3%%"
foreground = "%%color15%%"

[colors.main_window]
border = "%%color3%%"

[colors.settings_window]
border = "%%color3%%"

[colors.accents]
blue = "%%color6%%"
green = "%%color6%%"
magenta = "%%color6%%"
orange = "%%color6%%"
purple = "%%color6%%"
red = "%%color6%%"
yellow = "%%color6%%"
cyan = "%%color6%%"
