[meta]
version = 1
name = "Hellwal-Generated-Theme"
description = "Dynamically generated colors from wallpaper"
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
background = "%%color1%%"
foreground = "%%color7%%"
secondary_background = "%%color1%%"

[colors.list.item.selection]
background = "%%color3%%"
foreground = "%%color15%%"

[colors.main_window]
border = "%%color3%%"

[colors.settings_window]
border = "%%color3%%"

[colors.accents]
blue = "%%color14%%"
green = "%%color14%%"
magenta = "%%color14%%"
orange = "%%color14%%"
purple = "%%color14%%"
red = "%%color14%%"
yellow = "%%color14%%"
cyan = "%%color14%%"
