source = ~/.cache/hellwal/hyprlock.conf

general {
    grace = 1
    fractional_scaling = 2
    immediate_render = false
    fail_timeout = 0
    ignore_empty_input = true
}

animation {
    bezier = linear, 1, 1, 0, 0
    animation = fade, 1, 4, linear
}

background {
    monitor =
    path = $HOME/.cache/current_wallpaper.png

    color = rgb(0,0,0) # color will be rendered initially until path is available

    blur_size = 2
    blur_passes = 3
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.6000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}


# hours
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%I") </big></b>"
    color = $primary
    font_size = 112
    font_family = Gravitas One
    shadow_passes = 0
    shadow_size = 0

    position = 0, 220
    halign = center
    valign = center
}

# minutes
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = $primary
    font_size = 112
    font_family = Gravitas One
    shadow_passes = 0
    shadow_size = 0

    position = 0, 80
    halign = center
    valign = center
}

# day
label {
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%A')" </big></b>"
    color = $primary
    font_size = 18
    font_family = Inter

    position = 0, -15
    halign = center
    valign = center
}

# week
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
    color = $primary
    font_size = 14
    font_family = Inter

    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:100] echo " <b> ☼  $(brightnessctl -m | cut -d, -f4) </b>"
    color = $primary
    font_size = 15
    font_family = Inter
    position = 800, 50
    halign = left
    valign = bottom
}

label {
    monitor =
    text = cmd[update:100] echo "<b>   $(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{printf "%.0f%%", $2*100}') </b>"
    color = $primary
    font_size = 15
    font_family = Inter
    position = 0, 50
    halign = center
    valign = bottom
}

label {
    monitor =
    text = cmd[update:1000] echo "<b> $(cat /sys/class/power_supply/BAT0/capacity | awk '{if ($1 <= 20) print "󰁺"; else if ($1 <= 40) print "󰁼"; else if ($1 <= 60) print "󰁾"; else if ($1 <= 80) print "󰂀"; else print "󰁹"}')   $(cat /sys/class/power_supply/BAT0/capacity)% </b>"
    color = $primary
    font_size = 15
    font_family = Inter
    position = -800, 50
    halign = right
    valign = bottom
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 0

    dots_size = 0.28 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.64 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rouding = -1

    rounding = 20
    outer_color = bait
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = $primary
    fade_on_empty = true
    placeholder_text = <i>password, bruh?</i>
    fail_text = <i>password, bruh?</i>

    position = 0, 120
    halign = center
    valign = bottom
}
